# Generated by Django 2.2.2 on 2020-03-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_myuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_staff',
        ),
    ]
