# Generated by Django 2.2.2 on 2020-03-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_myuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_admin',
        ),
    ]
