# Generated by Django 2.2.2 on 2020-03-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_myuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default=True, max_length=30, unique=True, verbose_name='ユーザー名'),
        ),
    ]
