# Generated by Django 2.2.2 on 2020-03-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200320_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default=True, max_length=30, verbose_name='ユーザー名'),
        ),
    ]
