# Generated by Django 2.2.2 on 2020-03-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200321_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=255, unique=True, verbose_name='password'),
        ),
    ]
