# Generated by Django 2.2.2 on 2020-03-23 07:10

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='プランタイトル')),
                ('description', models.CharField(max_length=255, verbose_name='プランの説明')),
                ('image', models.ImageField(default='', upload_to='', verbose_name='イメージ画像')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='料金')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='タグ')),
            ],
            options={
                'verbose_name_plural': 'プラン',
            },
        ),
    ]
