# Generated by Django 2.2.2 on 2020-03-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
            ],
        ),
        migrations.AlterField(
            model_name='plan',
            name='tags',
            field=models.ManyToManyField(to='plan.Tag'),
        ),
    ]
